let campainsJson = [
  {
    "Date": "2019-11-01",
    "Tracker": "5xkzqgu",
    "Network": "Organic",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "APAC",
    "OS Name": "android",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "5xkzqgu",
    "Network": "Organic",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "APAC",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "5xkzqgu",
    "Network": "Organic",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "android",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": 10,
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": 167,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 84,
    "Weekly Active Users": 290,
    "Monthly Active Users": 703,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": 2,
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "5xkzqgu",
    "Network": "Organic",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": 83,
    "limit_ad_tracking_installs": 13,
    "limit_ad_tracking_install_rate": 0.1566,
    "Conversion": "",
    "Reattributions": "",
    "Sessions": 944,
    "Revenue Events": 11,
    "cohort_revenue": 284.2,
    "Revenue": 1200.5,
    "Daily Active Users": 563,
    "Weekly Active Users": 1998,
    "Monthly Active Users": 4896,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": 418,
    "Promotions_pressed (39v85t) (Events)": 137,
    "Casino_pressed (50dixt) (Events)": 264,
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": 11,
    "Deposit (94sjyd) (Revenue)": 1200.5,
    "Registration (a8j3o0) (Events)": 18,
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": 125,
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "5xkzqgu",
    "Network": "Organic",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "LATAM",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "5xkzqgu",
    "Network": "Organic",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "NA",
    "OS Name": "android",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "5xkzqgu",
    "Network": "Organic",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "NA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 5,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "793e3oe",
    "Network": "Maxbet_email",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "android",
    "impressions": "",
    "ctr": "",
    "Clicks": 5,
    "Installs": 1,
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": 0.2,
    "Reattributions": "",
    "Sessions": 15,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 5,
    "Weekly Active Users": 14,
    "Monthly Active Users": 30,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "793e3oe",
    "Network": "Maxbet_email",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": 1,
    "Installs": 1,
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": 1,
    "Reattributions": "",
    "Sessions": 7,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 3,
    "Weekly Active Users": 14,
    "Monthly Active Users": 30,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": 2,
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": 1,
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "5x4dwhr",
    "Network": "Snapchat Installs",
    "Campaign": "Rocket10_MaxBet_ios_ANI_RO_1403_mw_new2 (1023c279-df90-4d39-864d-1499ae9650c4)",
    "Adgroup": "App Install, Romania, All Genders, 18-35+ (f2b27d62-e917-4653-9464-5eceab7caf7d)",
    "Creative": "1 (21cf4eb1-da5c-401b-a51c-7823759fc031)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 3,
    "Monthly Active Users": 6,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "a1mzy1w",
    "Network": "Snapchat Installs",
    "Campaign": "Maxbet Install 09.19 (4db60e2e-152f-45d4-8374-d2075249a251)",
    "Adgroup": "Ad Set m-19+ 2,5 AP SprtFn (ce448d64-fef0-4dd2-b22f-ad77b999e5bb)",
    "Creative": "AdName0919 (4d63df34-e272-4523-92c6-3d5cafb8c1a3)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": 2,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 1,
    "Weekly Active Users": 3,
    "Monthly Active Users": 11,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "pwb6qia",
    "Network": "Snapchat Installs",
    "Campaign": "Maxbet Install (63ce25f4-e285-45fa-ba01-90845252453c)",
    "Adgroup": "As Set, m-19-25 CPL_2 AT_PL (b3b29abf-92a3-4e7e-888c-8fefdbab60bb)",
    "Creative": "Ads01 (abae5806-2cb8-42e7-8c9b-3333e49e9e4d)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 3,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "jnbdf06",
    "Network": "Snapchat Installs",
    "Campaign": "Maxbet Install (63ce25f4-e285-45fa-ba01-90845252453c)",
    "Adgroup": "Ad Set m-19-30 CPL_2 MLS_SP (3657478a-743c-4687-b8fb-280900e17e69)",
    "Creative": "Ads1.5 (47d34730-4837-420a-9837-c32b1a546f38)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "k90pxed",
    "Network": "Snapchat Installs",
    "Campaign": "Rocket10_MaxBet_ios_ANI_RO_1503_mw_new3 (3dbb2cf5-ff44-4b5e-8d0e-160f10b96de7)",
    "Adgroup": "Copy of App Install, Romania, All Genders, 18-35+ (5f2eaf11-f750-4e7b-b2e7-4349e8ba4e1a)",
    "Creative": "Copy of Copy of 1 (8772a082-a4e2-4014-8e19-db19820bf31e)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 2,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "33m41tg",
    "Network": "Snapchat Installs",
    "Campaign": "Install OR 1 (d9ad4f07-e652-4bdf-8592-4a50fef6d92e)",
    "Adgroup": "App Install, Romania, Male, 19+ (ffcdc61a-3689-4946-a2dd-0fc3c4880523)",
    "Creative": "slots (84871fba-ade3-4c57-8e6c-8d7eeb0a0a83)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 5,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "oo31vrr",
    "Network": "Snapchat Installs",
    "Campaign": "Rocket10_MaxBet_ios_ANI_RO_1403_mw_new5 (d8db058b-a410-45a8-a2d7-0dcee2fdd7cd)",
    "Adgroup": "App Install, Romania, All Genders, 18-35+ (b3b99768-4c45-4ee9-a291-a3cd06f65ed9)",
    "Creative": "1 (a250b37d-2af3-4811-8eda-0e49e76cec2f)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 4,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "1gae532",
    "Network": "Instagram Installs",
    "Campaign": "App_ios_install_new (23843976091050498)",
    "Adgroup": "LL8% (23843976139630498)",
    "Creative": "banner_jumpbef (23843976139640498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": 1,
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": 1,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 1,
    "Weekly Active Users": 1,
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "z92j7za",
    "Network": "Instagram Installs",
    "Campaign": "App_ios_install_new (23843976091050498)",
    "Adgroup": "LL3% (23843979166570498)",
    "Creative": "video_shincrown (23843979166600498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": 1,
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": 1,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 1,
    "Weekly Active Users": 1,
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "oa38xqe",
    "Network": "Facebook Installs",
    "Campaign": "Rocket10_MaxBet_ios_ANI_RO_0404_m_money (23843382122940498)",
    "Adgroup": "m 6 (23843382123290498)",
    "Creative": "1 — Копия — Копия (23843382124920498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "yz7p1qu",
    "Network": "Facebook Installs",
    "Campaign": "Rocket10_MaxBet_ios_ANI_RO_0404_m_money (23843382122940498)",
    "Adgroup": "m 6 (23843382123290498)",
    "Creative": "1 — Копия (23843382124830498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 4,
    "Monthly Active Users": 9,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "eqfxis8",
    "Network": "Facebook Installs",
    "Campaign": "App ios - reg_ 2lvl  OR (23843822532640498)",
    "Adgroup": "interests_forex_M 18-45 (23843822533830498)",
    "Creative": "video_36 (23843822533220498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 2,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "kx76cg7",
    "Network": "Off-Facebook Installs",
    "Campaign": "App ios - adult_deposits OR (23843955639570498)",
    "Adgroup": "RO_18_50 - i (23843964606420498)",
    "Creative": "video_shincrown (23843964606430498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": 1,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 1,
    "Weekly Active Users": 5,
    "Monthly Active Users": 5,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "3fljp8k",
    "Network": "Off-Facebook Installs",
    "Campaign": "App ios - Alex1 (23843626135130498)",
    "Adgroup": "avto-lal-Maxbet using fb_mobile_purchase (18-40) (23843626154030498)",
    "Creative": "video_36-v_40(20.09)-v_36(25.09)-i_new(18.10) (23843626154020498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 2,
    "Monthly Active Users": 10,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "3snhyiq",
    "Network": "Off-Facebook Installs",
    "Campaign": "App ios - all (21-50) AzartFriends_Val03 (23843572927830498)",
    "Adgroup": "RO - m18-40 Slots (23843745769710498)",
    "Creative": "video_shincrown (23843888997860498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": 1,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 1,
    "Weekly Active Users": 4,
    "Monthly Active Users": 32,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": 5,
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": 1,
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "pl3fdab",
    "Network": "Adavice",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "android",
    "impressions": "",
    "ctr": "",
    "Clicks": 1,
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "rot6ios",
    "Network": "Maxbet",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "APAC",
    "OS Name": "android",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "rot6ios",
    "Network": "Maxbet",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "android",
    "impressions": "",
    "ctr": "",
    "Clicks": 51,
    "Installs": 20,
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": 0.3922,
    "Reattributions": "",
    "Sessions": 352,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 194,
    "Weekly Active Users": 680,
    "Monthly Active Users": 1635,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": 1,
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "rot6ios",
    "Network": "Maxbet",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 3,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "rot6ios",
    "Network": "Maxbet",
    "Campaign": "unknown",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "windows",
    "impressions": "",
    "ctr": "",
    "Clicks": 2,
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": "",
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "z5qqpa0",
    "Network": "Facebook Messenger Installs",
    "Campaign": "App ios - m (18-24) Casino_Val02.11 (23843592784660498)",
    "Adgroup": "MT - m-18-24 (23843592784680498)",
    "Creative": "Default Name - 04 (23843592787310498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "9w1colp",
    "Network": "Facebook Messenger Installs",
    "Campaign": "App ios - reg OR all (23843819597890498)",
    "Adgroup": "all 18-45 (23843819598940498)",
    "Creative": "banner 14 (23843819597850498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 2,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "yl0bto1",
    "Network": "Facebook Messenger Installs",
    "Campaign": "App Installs_ios (23843223981240498)",
    "Adgroup": "ios_m (23843223981260498)",
    "Creative": "Video+text – Copy (23843229929380498)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "mxkf38j",
    "Network": "Yahoo Gemini Installs",
    "Campaign": "Maxbet App Install Oct19 (381395825)",
    "Adgroup": "Maxbet App Install Oct19 (9756469861)",
    "Creative": "_1e6e0a04d20f50967c64dac2d639a577 (35143877833)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 5,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "pnsrh0a",
    "Network": "Yahoo Gemini Installs",
    "Campaign": "Maxbet App Install Oct19 (381395825)",
    "Adgroup": "Maxbet App Install Oct19 (9756469861)",
    "Creative": "_1e6e0a04d20f50967c64dac2d639a577 (35143775160)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 3,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "5x9y622",
    "Network": "Yahoo Gemini Installs",
    "Campaign": "Maxbet App Install Oct19 (381395825)",
    "Adgroup": "Maxbet App Install Oct19 - New (9757633137)",
    "Creative": "_1e6e0a04d20f50967c64dac2d639a577 (35184626161)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "66masr6",
    "Network": "Yahoo Gemini Installs",
    "Campaign": "Maxbet App Install Oct19 (381395825)",
    "Adgroup": "Maxbet App Install Oct19 - New (9757633137)",
    "Creative": "_1e6e0a04d20f50967c64dac2d639a577 (35184607563)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": 2,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 1,
    "Weekly Active Users": 2,
    "Monthly Active Users": 2,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": 1,
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": 1,
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "ajbazs8",
    "Network": "Yahoo Gemini Installs",
    "Campaign": "Maxbet App Install Oct19 (381395825)",
    "Adgroup": "Maxbet App Install Oct19 - New (9757633137)",
    "Creative": "_1e6e0a04d20f50967c64dac2d639a577 (35184560803)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "wl6afrf",
    "Network": "Yahoo Gemini Installs",
    "Campaign": "Maxbet App Install Oct19 (381395825)",
    "Adgroup": "Maxbet App Install Oct19 - New (9757633137)",
    "Creative": "_1e6e0a04d20f50967c64dac2d639a577 (35184607536)",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": 1,
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "tl3g1ku",
    "Network": "Rocket10",
    "Campaign": 13404,
    "Adgroup": "1737_319_6516_8577_d906a3c13d87",
    "Creative": "{creative_id}",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "74an1yq",
    "Network": "Rocket10",
    "Campaign": "FB_Android",
    "Adgroup": "unknown",
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "android",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": 2,
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": 2,
    "Weekly Active Users": 11,
    "Monthly Active Users": 27,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "62evypk",
    "Network": "Rocket10",
    "Campaign": 8184,
    "Adgroup": 1004984,
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 1,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  },
  {
    "Date": "2019-11-01",
    "Tracker": "9zjn1pj",
    "Network": "Rocket10",
    "Campaign": 8184,
    "Adgroup": 946768,
    "Creative": "unknown",
    "region": "EMEA",
    "OS Name": "ios",
    "impressions": "",
    "ctr": "",
    "Clicks": "",
    "Installs": "",
    "limit_ad_tracking_installs": "",
    "limit_ad_tracking_install_rate": "",
    "Conversion": "",
    "Reattributions": "",
    "Sessions": "",
    "Revenue Events": "",
    "cohort_revenue": "",
    "Revenue": "",
    "Daily Active Users": "",
    "Weekly Active Users": "",
    "Monthly Active Users": 3,
    "gdpr_forgets": "",
    "Account_pressed (20kvqg) (Events)": "",
    "Promotions_pressed (39v85t) (Events)": "",
    "Casino_pressed (50dixt) (Events)": "",
    "android_simple_event (5bkcbj) (Events)": "",
    "Deposit (94sjyd) (Events)": "",
    "Deposit (94sjyd) (Revenue)": "",
    "Registration (a8j3o0) (Events)": "",
    "android_javascript_event (i71nor) (Events)": "",
    "Sports_pressed (m0la38) (Events)": "",
    "test_javascript_simple_event (orkhuv) (Events)": ""
  }
];

//let networkNames = ['Instagram Installs', 'Facebook Installs', 'Off-Facebook Installs'];
let networkNames = 'Instagram Installs';

const replaceKeys = (object) => {
  Object.keys(object).forEach(function (key) {
    let newKey = key.replace(' (a8j3o0) (Events)', '');
    let newKey2 = key.replace(' (94sjyd) (Events)', '');
    if (object[key] && typeof object[key] === 'object') {
      replaceKeys(object[key]);
    }
    if (key !== newKey) {
      object[newKey] = object[key];
      delete object[key];
    } else if (key !== newKey2) {
      object[newKey2] = object[key];
      delete object[key];
    }
  });
  return object
};

let newCampaignResults = replaceKeys(campainsJson);

const filterCampaignResultsByNetwork = (campaignResults, networkName) => {
  return campaignResults.filter(items => {
    return items.Network === networkName;
  });
};

const getColums = (campaignResult) => {
    return campaignResult.map(result => {
      let campaignResult = {};
      campaignResult.network = result.Network;
      campaignResult.id = getIdFromString(result.Creative);
      campaignResult.installs = result.Installs;
      campaignResult.registrations = result.Registration;
      campaignResult.deposit = result.Deposit;
      return campaignResult
    })
};

const getIdFromString = (string) => {
  let id = string.split(/[()]/);
  return id[1];
}

//console.log(newCampaignResults)
console.log(getColums(filterCampaignResultsByNetwork(newCampaignResults, networkNames)));
//console.log(getColums(newCampaignResults));